// src/nameMap.js
// 手工补全：英文名 -> 中文名（按你Excel中的英文名原样匹配）
export const NAME_ZH_MAP = {
  // ===== 男单 50 =====
  "Hugo CALDERANO": "雨果·卡尔德拉诺",
  "Truls MOREGARD": "特鲁尔斯·莫雷加德",
  "HARIMOTO Tomokazu": "张本智和",
  "LEBRUN Felix": "费利克斯·勒布伦",
  "MATSUSHIMA Sora": "松岛辉空",
  "LIN Yun-Ju": "林昀儒",
  "Patrick FRANZISKA": "帕特里克·弗朗西斯卡",
  "Dang QIU": "邱党",
  "JANG Woojin": "张禹珍",
  "Benedikt DUDA": "本尼迪克特·杜达",
  "Darko JORGIC": "达科·约奇克",
  "AN Jaehyun": "安宰贤",
  "Simon GAUZY": "西蒙·高茨",
  "Alexis LEBRUN": "亚历克西·勒布伦",
  "Kanak JHA": "卡纳克·贾哈",
  "Dimitrij OVTCHAROV": "迪米特里·奥恰洛夫",
  "Tomislav PUCAR": "托米斯拉夫·普卡尔",
  "Anton KALLBERG": "安东·卡尔伯格",
  "SHINOZUKA Hiroto": "筱塚大登",
  "Omar ASSAR": "奥马尔·阿萨尔",
  "COTON Flavien": "弗拉维安·科唐",
  "Quadri ARUNA": "夸德里·阿鲁纳",
  "Manav THAKKAR": "马纳夫·塔卡尔",
  "PORET Thibault": "蒂博·波雷",
  "TANAKA Yuta": "田中佑汰",
  "REDZIMSKI Milosz": "米洛什·雷津斯基",
  "Jonathan GROTH": "乔纳森·格罗斯",
  "Kristian KARLSSON": "克里斯蒂安·卡尔松",
  "LUM Nicholas": "林文政",
  "IONESCU Eduard": "爱德华·约内斯库",
  "Ricardo WALTHER": "里卡多·瓦尔特",
  "WONG Chun Ting": "黄镇廷",
  "KAO Cheng-Jui": "高承睿",
  "Lilian BARDET": "利利安·巴尔代",
  "LUU Finn": "卢伟",
  "Youssef ABDELAZIZ": "优素福·阿卜杜勒阿齐兹",
  "CHO Daeseong": "赵大成",
  "Vladimir SIDORENKO": "弗拉基米尔·西多连科",
  "FENG Yi-Hsin": "冯翊新",
  "Leo DE NODREST": "莱奥·德·诺德雷斯特",
  "Aditya SAREEN": "阿迪蒂亚·萨林",
  "HAMADA Kazuki": "滨田一辉",
  "Sathiyan GNANASEKARAN": "萨蒂扬·格纳纳塞卡兰",
  "Adrien RASSENFOSSE": "阿德里安·拉森福斯",
  "BAE Hwan": "裴焕",
  "YOSHIYAMA Ryoichi": "吉山僚一",
  "Anders LIND": "安德斯·林德",
  "TOGAMI Shunsuke": "户上隼辅",
  "OH Junsung": "吴俊成",
  "UDA Yukiya": "宇田幸矢",
  "CHUQIN WANG": "王楚钦",
  "SHIDONG LIN": "林诗栋",
  "JINGKUN LIANG": "梁靖崑",
  "PENG XIANG": "向鹏",
  "QIHAO ZHOU": "周启豪",
  "YUANYU CHEN": "陈垣宇",
  "YOUZHENG HUANG": "黄友政",
  "JUNSONG CHEN": "陈俊松",
  "RUIBO WEN": "温瑞博",
  "GAOYUAN LIN": "林高远",

  // ===== 女单 50 =====
  "ZHU Yuling": "朱雨玲",
  "HARIMOTO Miwa": "张本美和",
  "ITO Mima": "伊藤美诚",
  "HAYATA Hina": "早田希娜",
  "HASHIMOTO Honoka": "桥本帆乃香",
  "SHIN Yubin": "申裕斌",
  "ODO Satsuki": "大藤沙月",
  "NAGASAKI Miyu": "长崎美柚",
  "JOO Cheonhui": "朱芊熙",
  "Sabine WINTER": "萨宾·温特",
  "Ying HAN": "韩莹",
  "Adriana DIAZ": "阿德里安娜·迪亚兹",
  "Bruna TAKAHASHI": "布鲁娜·高桥",
  "CHENG I-Ching": "郑怡静",
  "KIHARA Miyuu": "木原美悠",
  "SATO Hitomi": "佐藤瞳",
  "Hana GODA": "哈娜·古达",
  "YUAN Jia Nan": "袁嘉楠",
  "KIM Nayeong": "金娜英",
  "Bernadette SZOCS": "贝尔纳黛特·斯佐科斯",
  "Prithika PAVADE": "普利蒂卡·帕瓦德",
  "Elizabeta SAMARA": "伊丽莎贝塔·萨马拉",
  "Sofia POLCANOVA": "索菲亚·波尔卡诺娃",
  "LEE Eunhye": "李恩惠",
  "ZENG Jian": "曾尖",
  "YOKOI Sakura": "横井咲樱",
  "DOO Hoi Kem": "杜凯琹",
  "LIU Yangzi": "刘杨子",
  "Lily ZHANG": "张安",
  "AKAE Kaho": "赤江加穗",
  "SHIBATA Saki": "柴田沙纪",
  "Sreeja AKULA": "斯里贾·阿库拉",
  "HURSEY Anna": "安娜·赫西",
  "Dina MESHREF": "迪娜·梅谢列夫",
  "Manika BATRA": "玛妮卡·巴特拉",
  "Linda BERGSTROM": "琳达·伯格斯特隆",
  "Mo ZHANG": "张墨",
  "KAUFMANN Annett": "安妮特·考夫曼",
  "Minhyung JEE": "池旼亨",
  "HIRANO Miu": "平野美宇",
  "LI Yu-Jhun": "李昱谆",
  "PSIHOGIOS Constantina": "康斯坦蒂娜·普西霍吉奥斯",
  "Lea RAKOVAC": "莉娅·拉科瓦茨",
  "Jieni SHAO": "邵洁妮",
  "Fu YU": "付玉",
  "YEH Yi-Tian": "叶伊恬",
  "Xiaona SHAN": "单晓娜",
  "Amy WANG": "王艾米",
  "LUTZ Charlotte": "夏洛特·卢茨",
  "キム・ソンジン KIM Seongjin": "金成振"
};

// 补充：中国女单（本地汇总导入后的英文名映射）
Object.assign(NAME_ZH_MAP, {
  "YINGSHA SUN": "孙颖莎",
  "MANYU WANG": "王曼昱",
  "YIDI WANG": "王艺迪",
  "XINGTONG CHEN": "陈幸同",
  "MAN KUAI": "蒯曼",
  "YI CHEN": "陈熠",
  "ZHUOJIA HE": "何卓佳",
  "XUNYAO SHI": "石洵瑶",
  "YUXUAN QIN": "覃予萱",
  "WEISHAN LIU": "刘炜珊",

  // 兼容首字母大写写法
  "Yingsha Sun": "孙颖莎",
  "Manyu Wang": "王曼昱",
  "Yidi Wang": "王艺迪",
  "Xingtong Chen": "陈幸同",
  "Man Kuai": "蒯曼",
  "Yi Chen": "陈熠",
  "Zhuojia He": "何卓佳",
  "Xunyao Shi": "石洵瑶",
  "Yuxuan Qin": "覃予萱",
  "Weishan Liu": "刘炜珊"
});
